# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: ${{ parameters.node_version }}
    displayName: 'Install Node.js'

  - script: >
      npm link 
    displayName: 'Restore Packages'

  - script: >
      npm run build && 
      npm test
    displayName: 'Build & Unit Test'

  - script: >
      npm install -g rimraf &&
      npm install -g yarn
    displayName: 'Prepare Full-Cycle Tests'
      
  - script: >
      rimraf ./demo &&
      mkdir demo &&
      cd demo &&
      ipack new vue &&
      ipack &&
      ipack -d --no-sourcemaps
    displayName: 'Full-Cycle Test: vue'

  - script: >
      rimraf ./demo &&
      mkdir demo &&
      cd demo &&
      ipack new react &&
      ipack &&
      ipack -d --no-sourcemaps
    displayName: 'Full-Cycle Test: react'

  - script: >
      rimraf ./demo &&
      mkdir demo &&
      cd demo &&
      ipack new blazor &&
      ipack &&
      ipack -d --no-sourcemaps
    displayName: 'Full-Cycle Test: blazor'

  - script: >
      rimraf ./demo &&
      mkdir demo &&
      cd demo &&
      ipack new preact &&
      ipack &&
      ipack -d --no-sourcemaps
    displayName: 'Full-Cycle Test: preact'

  - script: >
      rimraf ./demo &&
      mkdir demo &&
      cd demo &&
      ipack new inferno &&
      ipack &&
      ipack -d --no-sourcemaps
    displayName: 'Full-Cycle Test: inferno'
