name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm restore, build & test
      run: |
        npm link
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Prepare for instapack full-cycle tests
      run: |
        npm install -g rimraf
        ipack set package-manager npm
    - name: instapack full-cycle test - Vue
      run: |
        rimraf ./demo
        mkdir demo
        cd demo
        ipack new vue
        ipack -db
        ipack 
    - name: instapack full-cycle test - React
      run: |
        rimraf ./demo
        mkdir demo
        cd demo
        ipack new react
        ipack -db
        ipack 
    - name: instapack full-cycle test - Blazor
      run: |
        rimraf ./demo
        mkdir demo
        cd demo
        ipack new blazor
        ipack -db
        ipack 
    - name: instapack full-cycle test - Preact
      run: |
        rimraf ./demo
        mkdir demo
        cd demo
        ipack new preact
        ipack -db
        ipack 
    - name: instapack full-cycle test - Inferno
      run: |
        rimraf ./demo
        mkdir demo
        cd demo
        ipack new inferno
        ipack -db
        ipack 
